Feature to use public providers for ethereum based networks
prokey-io/prokey-webcore pull request #64
Opened 2022-08-25 16:36 UTC by houman-sanati

2022-08-28 06:07 UTC, hadideveloper requested changes

2022-08-29 07:36 UTC, houman-sanati commented on data/BlockchainProviders.json
> +                    "name": "prokey-blockbook",
https://github.com/prokey-io/prokey-webcore/pull/64/commits/28ecec0b38579551e9692d93817d1fff08c0a664

2022-08-29 07:36 UTC, houman-sanati commented on data/BlockchainProviders.json
>                      "name": "prokey-chaino"
https://github.com/prokey-io/prokey-webcore/pull/64/commits/28ecec0b38579551e9692d93817d1fff08c0a664

2022-08-30 05:12 UTC, hadideveloper approved these changes

2022-08-30 05:12 UTC, merged